version: '2'

services:

  elasticsearch:
    image: elasticsearch:2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
    volumes:
      - ./pg_data_dev:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: /start-dev.sh
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=True
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
      - elasticsearch
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:latest
    restart: always

  grpc:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: /start-grpc.sh
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx_dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
    command: celery -A opac_ssm.taskapp worker -l DEBUG
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx_dev
    volumes:
      - .:/app

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    user: django
    restart: always
    depends_on:
      - postgres
      - redis
    command: celery -A opac_ssm.taskapp beat -l DEBUG
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_SECRET_KEY=sdal#^4pih^ekewqtq8k_m9lin#136olq-_p086wsu-)=8=ns!
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=False
      - USE_DOCKER=yes
      - HAYSTACK_CONNECTIONS_HOST=elasticsearch
      - HAYSTACK_CONNECTIONS_PORT=9200
      - HAYSTACK_CONNECTIONS_INDEX=opac_ssm_idx_dev
    volumes:
      - .:/app
